package com.resume;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

public class Main {
    public static void main(String[] args) {

        //Variables necessary for the resume
        String name;
        String email;
        String phone;
        String city;
        String summary;
        String skill1;
        String skill2;
        String skill3;
        String skill4;
        String skill5;
        String skill6;
        String skill7;
        String skill8;
        String jobTitle1;
        String company1;
        String startDate1;
        String endDate1;
        String jobBullet1;
        String jobBullet2;
        String jobBullet3;
        String jobBullet4;
        String jobTitle2;
        String company2;
        String startDate2;
        String endDate2;
        String jobBullet5;
        String jobBullet6;
        String jobBullet7;
        String jobBullet8;
        String university1;
        String degree1;
        String university2;
        String degree2;
        String degree3;
        String degree4;
        String cert1;
        String cert2;
        String cert3;
        String cert4;
        String vol1;
        String vol2;
        String vol3;
        String vol4;

        //Captures customer input for the resume
        Scanner scan = new Scanner(System.in);
        System.out.println("Please enter your full name:");
        name = scan.nextLine();
        System.out.println("Please enter your email address:");
        email = scan.nextLine();
        System.out.println("Please enter your phone number:");
        phone = scan.nextLine();
        System.out.println("Please enter the city where you live:");
        city = scan.nextLine();
        System.out.println("Please enter a Summary about yourself:");
        summary = scan.nextLine();
        System.out.println("Please enter a skill you possess:");
        skill1 = scan.nextLine();
        System.out.println("Please enter a skill you possess:");
        skill2 = scan.nextLine();
        System.out.println("Please enter a skill you possess:");
        skill3 = scan.nextLine();
        System.out.println("Please enter a skill you possess:");
        skill4 = scan.nextLine();
        System.out.println("Please enter a skill you possess:");
        skill5 = scan.nextLine();
        System.out.println("Please enter a skill you possess:");
        skill6 = scan.nextLine();
        System.out.println("Please enter a skill you possess:");
        skill7 = scan.nextLine();
        System.out.println("Please enter a skill you possess:");
        skill8 = scan.nextLine();
        System.out.println("Please enter the Job Title of your most recent job:");
        jobTitle1 = scan.nextLine();
        System.out.println("Please enter the Company of your most recent job:");
        company1 = scan.nextLine();
        System.out.println("Please enter the Start Date of your most recent employment:");
        startDate1 = scan.nextLine();
        System.out.println("Please enter the End Date of your most recent employment:");
        endDate1 = scan.nextLine();
        System.out.println("Please enter the first accomplishment of your most recent employment:");
        jobBullet1 = scan.nextLine();
        System.out.println("Please enter the second accomplishment of your most recent employment:");
        jobBullet2 = scan.nextLine();
        System.out.println("Please enter the third accomplishment of your most recent employment:");
        jobBullet3 = scan.nextLine();
        System.out.println("Please enter the fourth accomplishment of your most recent employment:");
        jobBullet4 = scan.nextLine();
        System.out.println("Please enter the Job Title of your next most recent job:");
        jobTitle2 = scan.nextLine();
        System.out.println("Please enter the Company of your next most recent job:");
        company2 = scan.nextLine();
        System.out.println("Please enter the Start Date of your next most recent employment:");
        startDate2 = scan.nextLine();
        System.out.println("Please enter the End Date of your next most recent employment:");
        endDate2 = scan.nextLine();
        System.out.println("Please enter the first accomplishment of your next most recent employment:");
        jobBullet5 = scan.nextLine();
        System.out.println("Please enter the second accomplishment of your next most recent employment:");
        jobBullet6 = scan.nextLine();
        System.out.println("Please enter the third accomplishment of your next most recent employment:");
        jobBullet7 = scan.nextLine();
        System.out.println("Please enter the fourth accomplishment of your next most recent employment:");
        jobBullet8 = scan.nextLine();
        System.out.println("Please enter the first University you attended:");
        university1 = scan.nextLine();
        System.out.println("Please enter the degree you achieved at your first University:");
        degree1 = scan.nextLine();
        System.out.println("Please enter any subsequent degrees earned at this University:");
        degree2 = scan.nextLine();
        System.out.println("Please enter the second University you attended:");
        university2 = scan.nextLine();
        System.out.println("Please enter the degree you achieved at your first University:");
        degree3 = scan.nextLine();
        System.out.println("Please enter any subsequent degrees earned at this University:");
        degree4 = scan.nextLine();
        System.out.println("Please enter any Industry Certifications you have achieved:");
        cert1 = scan.nextLine();
        System.out.println("Please enter any Industry Certifications you have achieved:");
        cert2 = scan.nextLine();
        System.out.println("Please enter any Industry Certifications you have achieved:");
        cert3 = scan.nextLine();
        System.out.println("Please enter any Industry Certifications you have achieved:");
        cert4 = scan.nextLine();
        System.out.println("Please enter any Volunteer Work:");
        vol1 = scan.nextLine();
        System.out.println("Please enter any Volunteer Work:");
        vol2 = scan.nextLine();
        System.out.println("Please enter any Volunteer Work:");
        vol3 = scan.nextLine();
        System.out.println("Please enter any Volunteer Work:");
        vol4 = scan.nextLine();


        //Checks for existing file and deletes it if it exists.  Creates a new file if one doesn't already exist and
        //overwrites it with the new data and saves the html file.
        try {
            File oldFile = new File("/home/mintuser/Documents/index.html");

            if (oldFile.exists()) {
                oldFile.delete();
            } else {
                FileWriter writer = new FileWriter("/home/mintuser/Documents/index.html", true);
            }


            FileWriter writer = new FileWriter("/home/mintuser/Documents/index.html", true);
            writer.write("<!DOCTYPE HTML>");
            writer.write("\r\n");
            writer.write("<html>");
            writer.write("\r\n");
            writer.write("<head>");
            writer.write("\r\n");
            writer.write("<title>");
            writer.write("\r\n");
            writer.write("Resume " + "- " + name);
            writer.write("\r\n");
            writer.write("</title>");
            writer.write("\r\n");
            writer.write("</head>");
            writer.write("\r\n");
            writer.write("<body style=\"max-width: 50%; padding-left: 25%;\">");
            writer.write("\r\n");
            writer.write("<h1 style=\"text-align:center;\">" + name + "</h1>");
            writer.write("\r\n");
            writer.write("<h4 style=\"text-align:center;\">" + email + " | " + phone + " | " + city +  "</h4>");
            writer.write("\r\n");
            writer.write("<h2>Summary</h2><hr><br>");
            writer.write("\r\n");
            writer.write("<div wrap-text:normal;>");
            writer.write("\r\n");
            writer.write(summary);
            writer.write("\r\n");
            writer.write("</div></br>");
            writer.write("\r\n");
            writer.write("<h2>Skills</h2><hr><br>");
            writer.write("\r\n");
            writer.write("<table width=\"100%\">");
            writer.write("\r\n");
            writer.write("<col style=\"width:50%\">");
            writer.write("\r\n");
            writer.write("<col style=\"width:50%\">");
            writer.write("\r\n");
            writer.write("<tr>");
            writer.write("\r\n");
            writer.write("<td>");
            writer.write("\r\n");
            writer.write("<ul style=\"display: inline block; padding-left: 180px; text-align: left;\">");
            writer.write("\r\n");
            writer.write("<li>" + skill1 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + skill2 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + skill3 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + skill4 + "</li>");
            writer.write("\r\n");
            writer.write("</ul>");
            writer.write("\r\n");
            writer.write("</td>");
            writer.write("\r\n");
            writer.write("<td>");
            writer.write("\r\n");
            writer.write("<ul style=\"display: inline block; padding-left: 180px; text-align: left;\">");
            writer.write("\r\n");
            writer.write("<li>" + skill5 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + skill6 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + skill7 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + skill8 + "</li>");
            writer.write("\r\n");
            writer.write("</ul>");
            writer.write("\r\n");
            writer.write("</td>");
            writer.write("\r\n");
            writer.write("</tr>");
            writer.write("\r\n");
            writer.write("</table>");
            writer.write("\r\n");
            writer.write("<h2>Experience</h2><hr><br>");
            writer.write("\r\n");
            writer.write("<table width=\"100%\">");
            writer.write("\r\n");
            writer.write("<col style=\"width:30%\">");
            writer.write("\r\n");
            writer.write("<col style=\"width:70%\">");
            writer.write("<tr>");
            writer.write("\r\n");
            writer.write("<td>");
            writer.write("\r\n");
            writer.write("<p><strong>" + company1 + "</strong><br>" + jobTitle1 + "<br>" + startDate1 + " - " + endDate1 + "<p>");
            writer.write("\r\n");
            writer.write("</td>");
            writer.write("\r\n");
            writer.write("<td style=\"display: inline block; padding-left: 250px; text-align: left;\">");
            writer.write("\r\n");
            writer.write("<ul>");
            writer.write("\r\n");
            writer.write("<li>" + jobBullet1 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + jobBullet2 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + jobBullet3 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + jobBullet4 + "</li>");
            writer.write("\r\n");
            writer.write("</ul>");
            writer.write("\r\n");
            writer.write("</td>");
            writer.write("\r\n");
            writer.write("</tr>");
            writer.write("\r\n");
            writer.write("<tr>");
            writer.write("\r\n");
            writer.write("<td>");
            writer.write("\r\n");
            writer.write("<p><strong>" + company2 + "</strong><br>" + jobTitle2 + "<br>" + startDate2 + " - " + endDate2 + "<p>");
            writer.write("\r\n");
            writer.write("</td>");
            writer.write("\r\n");
            writer.write("<td style=\"display: inline block; padding-left: 250px; text-align: left;\">");
            writer.write("\r\n");
            writer.write("<ul>");
            writer.write("\r\n");
            writer.write("<li>" + jobBullet5 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + jobBullet6 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + jobBullet7 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + jobBullet8 + "</li>");
            writer.write("\r\n");
            writer.write("</ul>");
            writer.write("\r\n");
            writer.write("</td>");
            writer.write("\r\n");
            writer.write("</tr>");
            writer.write("</table>");
            writer.write("\r\n");
            writer.write("<h2>Education and Training</h2><hr><br>");
            writer.write("\r\n");
            writer.write("<table width=\"100%\">");
            writer.write("\r\n");
            writer.write("<col style=\"width:30%\">");
            writer.write("\r\n");
            writer.write("<col style=\"width:70%\">");
            writer.write("<tr>");
            writer.write("\r\n");
            writer.write("<td valign= \"top\">");
            writer.write("\r\n");
            writer.write("<p><strong>" + university1 + "</strong><br>" + degree1 + "<br>" + degree2 + "<p>");
            writer.write("\r\n");
            writer.write("</td>");
            writer.write("\r\n");
            writer.write("<td style=\"display: inline block; padding-left: 250px; text-align: left;\">");
            writer.write("\r\n");
            writer.write("<strong>Industry Certifications:</strong></br>");
            writer.write("\r\n");
            writer.write("<ul>");
            writer.write("\r\n");
            writer.write("<li>" + cert1 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + cert2 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + cert3 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + cert4 + "</li>");
            writer.write("\r\n");
            writer.write("</ul>");
            writer.write("\r\n");
            writer.write("</td>");
            writer.write("\r\n");
            writer.write("</tr>");
            writer.write("\r\n");
            writer.write("<tr>");
            writer.write("\r\n");
            writer.write("<td valign= \"top\">");
            writer.write("\r\n");
            writer.write("<p><strong>" + university2 + "</strong><br>" + degree3 + "<br>" + degree4 + "<p>");
            writer.write("\r\n");
            writer.write("</td>");
            writer.write("\r\n");
            writer.write("<td style=\"display: inline block; padding-left: 250px; text-align: left;\">");
            writer.write("\r\n");
            writer.write("<strong>Volunteer Work:</strong><br>");
            writer.write("\r\n");
            writer.write("<ul>");
            writer.write("\r\n");
            writer.write("<li>" + vol1 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + vol2 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + vol3 + "</li>");
            writer.write("\r\n");
            writer.write("<li>" + vol4 + "</li>");
            writer.write("\r\n");
            writer.write("</ul>");
            writer.write("\r\n");
            writer.write("</td>");
            writer.write("\r\n");
            writer.write("</tr>");
            writer.write("</table>");
            writer.write("</body>");
            writer.write("\r\n");
            writer.write("</html>");
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
